--- #YAML:1.0
name:               WWW-Mailchimp
version:            0.002
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:             0
    LWP:              0
    Moose:            0.93
    URI:              0
    URI::QueryParam:  0
resources:
    bugtracker:  http://rt.cpan.org/NoAuth/Bugs.html?Dist=WWW-Mailchimp
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/arcanez/www-mailchimp
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
